export const tasks = [
  {
    id: 1,
    description: 'Pay path his money',
    status: 'on hold',
    priority: 'High',
    date: new Date('2021-10-05').getTime(),
  },
  {
    id: 2,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-10-02'),
  },
  {
    id: 3,
    description: 'hang out with friends for about 1hr',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-08-01'),
  },
  {
    id: 4,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-04-02'),
  },
  {
    id: 5,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-06-05'),
  },
  {
    id: 6,
    description: 'work on my project',
    status: 'on hold',
    priority: 'Low',
    date: new Date('2023-11-02'),
  },
  {
    id: 7,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-11'),
  },
  {
    id: 8,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-10-12'),
  },
  {
    id: 9,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-08-11'),
  },
  {
    id: 10,
    description: 'chat with friends',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-05-10'),
  },
  {
    id: 11,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-07'),
  },
  {
    id: 12,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-18'),
  },
  {
    id: 13,
    description: 'work on my project',
    status: 'on hold',
    priority: 'Low',
    date: new Date('2023-11-08'),
  },
  {
    id: 14,
    description: 'spend some time with friends',
    status: 'on hold',
    priority: 'Low',
    date: new Date('2023-11-09'),
  },
  {
    id: 15,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-06'),
  },
  {
    id: 16,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-05'),
  },
  {
    id: 17,
    description: 'hang out with friends for about 1hr',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-11-04'),
  },
  {
    id: 18,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-03'),
  },
  {
    id: 19,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-02'),
  },
  {
    id: 20,
    description: 'work on my project',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-01'),
  },
  {
    id: 21,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-15'),
  },
  {
    id: 22,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-01'),
  },
  {
    id: 23,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-10'),
  },
  {
    id: 24,
    description: 'hang out with friends for about 1hr',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-11-17'),
  },
  {
    id: 25,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-12'),
  },
  {
    id: 26,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-06'),
  },
  {
    id: 27,
    description: 'work on my project',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-05'),
  },
  {
    id: 28,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-05'),
  },
  {
    id: 29,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-02'),
  },
  {
    id: 30,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-11'),
  },
  {
    id: 31,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-01'),
  },
  {
    id: 32,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-10'),
  },
  {
    id: 33,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-12'),
  },
  {
    id: 34,
    description: 'hang out with friends for about 1hr',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-11-16'),
  },
  {
    id: 35,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-14'),
  },
  {
    id: 36,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-13'),
  },
  {
    id: 37,
    description: 'work on my project',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-11'),
  },
  {
    id: 38,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-16'),
  },
  {
    id: 39,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-01'),
  },
  {
    id: 40,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-02'),
  },
  {
    id: 41,
    description: 'hang out with friends for about 1hr',
    status: 'todo',
    priority: 'Medium',
    date: new Date('2023-11-05'),
  },
  {
    id: 42,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-10'),
  },
  {
    id: 43,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-11'),
  },
  {
    id: 44,
    description: 'work on my project',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-09'),
  },
  {
    id: 45,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-11-10'),
  },
  {
    id: 46,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-11-13'),
  },
  {
    id: 47,
    description: 'fill my 12.5kg gas',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-11-12'),
  },
  {
    id: 48,
    description: 'cut my hair',
    status: 'todo',
    priority: 'High',
    date: new Date('2023-11-10'),
  },
  {
    id: 49,
    description: 'refill my car fuel tank',
    status: 'in progress',
    priority: 'High',
    date: new Date('2023-11-12'),
  },
  {
    id: 50,
    description: 'work on my project',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2023-10-10'),
  },
  {
    id: 51,
    description: 'spend some time with friends',
    status: 'Done',
    priority: 'Low',
    date: new Date('2023-07-01'),
  },
  {
    id: 52,
    description: 'do some shopping at maxland shopping mall',
    status: 'Done',
    priority: 'High',
    date: new Date('2023-09-10'),
  },
  {
    id: 53,
    description: 'wake buchi up',
    status: 'in progress',
    priority: 'Low',
    date: new Date('2021-10-11'),
  },
];
